FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    curl && \
    pip install --no-cache-dir scikit-learn pandas

WORKDIR /app

COPY ml_model /app/ml_model
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "ml_model/ml_main.py"]
